apiVersion: v2
name: ark-api
description: ARK API service with Gateway API HTTPRoute integration
type: application
version: 0.1.52
appVersion: 0.1.52
annotations:
  ark.mckinsey.com/service: ark-api
  ark.mckinsey.com/resources: service
