apiVersion: v2
name: localhost-gateway
description: Ark Gateway for Local Development
type: application
version: 0.1.51
appVersion: 0.1.51
annotations:
  category: Networking
  licenses: Apache-2.0
  ark.mckinsey.com/service: localhost-gateway
  ark.mckinsey.com/resources: service
  installs: Gateway API CRDs, nginx-gateway-fabric controller, localhost Gateway
  usage: Provides *.namespace.127.0.0.1.nip.io:8080 routing for all services
dependencies:
  - name: nginx-gateway-fabric
    version: 2.0.2
    repository: oci://ghcr.io/nginx/charts
