{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ark-broker.serviceAccountName" . }}
  labels:
    {{- include "ark-broker.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}