resources:
# All RBAC will be applied under this service account in
# the deployment namespace. You may comment out this resource
# if your manager will use a service account that exists at
# runtime. Be sure to update RoleBinding and ClusterRoleBinding
# subjects if changing service account names.
- service_account.yaml
- ark_controller_role.yaml
- ark_controller_role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- webhook_role.yaml
# The following RBAC configurations are used to protect
# the metrics endpoint with authn/authz. These configurations
# ensure that only authorized users and service accounts
# can access the metrics endpoint. Comment the following
# permissions if you want to disable this protection.
# More info: https://book.kubebuilder.io/reference/metrics.html
- metrics_auth_role.yaml
- metrics_auth_role_binding.yaml
- metrics_reader_role.yaml
- metrics_service.yaml
# For each CRD, "Admin", "Editor" and "Viewer" roles are scaffolded by
# default, aiding admins in cluster management. Those roles are
# not used by the ark itself. You can comment the following lines
# if you do not want those helpers be installed with your Project.
- evaluator_admin_role.yaml
- evaluator_editor_role.yaml
- evaluator_viewer_role.yaml
- memory_admin_role.yaml
- memory_editor_role.yaml
- memory_viewer_role.yaml
- team_admin_role.yaml
- team_editor_role.yaml
- team_viewer_role.yaml
- tool_admin_role.yaml
- tool_editor_role.yaml
- tool_viewer_role.yaml
- model_admin_role.yaml
- model_editor_role.yaml
- model_viewer_role.yaml
- query_admin_role.yaml
- query_editor_role.yaml
- query_viewer_role.yaml
- agent_admin_role.yaml
- agent_editor_role.yaml
- agent_viewer_role.yaml
